-- 밥서라이크 공개 평가 테이블
create table if not exists public.feedback (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  rating smallint not null check (rating between 1 and 5),
  comment text not null default '' check (char_length(comment) <= 500),
  game_version varchar(20) not null,
  result varchar(20) not null check (result in ('none', 'victory', 'defeat')),
  survival_time integer not null default 0 check (survival_time >= 0),
  final_level integer not null default 1 check (final_level >= 1),
  kill_count integer not null default 0 check (kill_count >= 0),
  max_body_stage varchar(20) not null default '가벼움'
);

alter table public.feedback enable row level security;

-- 익명/로그인 사용자는 공개 평가를 읽고 새 평가만 추가할 수 있다.
drop policy if exists "public can read feedback" on public.feedback;
create policy "public can read feedback"
on public.feedback for select
to anon, authenticated
using (true);

drop policy if exists "public can insert valid feedback" on public.feedback;
create policy "public can insert valid feedback"
on public.feedback for insert
to anon, authenticated
with check (
  rating between 1 and 5
  and char_length(comment) <= 500
  and result in ('none', 'victory', 'defeat')
  and survival_time >= 0
  and final_level >= 1
  and kill_count >= 0
);

-- UPDATE/DELETE 정책을 만들지 않아 익명 사용자의 수정과 삭제는 허용되지 않는다.
grant select, insert on table public.feedback to anon, authenticated;
grant usage, select on sequence public.feedback_id_seq to anon, authenticated;
revoke update, delete on table public.feedback from anon, authenticated;

create index if not exists feedback_created_at_idx on public.feedback (created_at desc);
